version: '3'
services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 5mb --maxmemory-policy volatile-ttl

  redis-slave:
    image: redis:latest
    container_name: redis-slave
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379 --appendonly yes --maxmemory 5mb --maxmemory-policy volatile-ttl
    depends_on:
      - redis-master